***BAG OF WORDS***

In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.DataFrame({'text':['People watch cricket','cricket watch cricket','people write comment','cricket write comment'],'output':[1,1,0,0]})

In [21]:
df

text  output
0   People watch cricket       1
1  cricket watch cricket       1
2   people write comment       0
3  cricket write comment       0

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [23]:
bow = cv.fit_transform(df['text'])

In [24]:
#VOCAB
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'cricket': 1, 'write': 4, 'comment': 0}


In [25]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]


In [26]:
cv.transform(["Cricket watch and write comment of cricket"]).toarray()

array([[1, 2, 0, 1, 1]])

***BAG OF N GRAM***

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,2))

In [28]:
bow = cv.fit_transform(df['text'])

In [29]:
#VOCAB
print(len(cv.vocabulary_))

11


In [30]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 0 0 1 1 0 1 1 0 0]]
[[0 2 1 0 0 0 0 1 1 0 0]]


***TF-IDF***

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
tfidf = tf.fit_transform(df['text']).toarray()

In [35]:
print(tf.idf_)
print(tf.get_feature_names_out())

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
['comment' 'cricket' 'people' 'watch' 'write']
